spring:
  config:
    activate:
      on-profile: prod

  cloud:
    consul:
      enabled: true
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        hostname: karvio-api-gateway-service
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        service-name: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework.cloud.consul: WARN
    org.springframework.cloud.gateway: WARN