server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}

spring:
  main:
    web-application-type: reactive
  application:
    name: karvio-api-gateway-service

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: ${CORS_ALLOWED_ORIGINS}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                allowedHeaders: "*"
                exposedHeaders:
                  - Authorization
                allowCredentials: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: karvio-auth-service-route
              uri: lb://karvio-auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: karvio-auth-service-circuitbreaker
                    fallbackUri: /fallback/karvio-auth-service-fallback
            - id: karvio-car-service-route
              uri: lb://karvio-car-service
              predicates:
                - Path=/car/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: karvio-car-service-circuitbreaker
                    fallbackUri: /fallback/karvio-car-service-fallback
            - id: karvio-document-service-route
              uri: lb://karvio-document-service
              predicates:
                - Path=/document/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: karvio-document-service-circuitbreaker
                    fallbackUri: /fallback/karvio-document-service-fallback
            - id: karvio-notification-service-route
              uri: lb://karvio-notification-service
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: karvio-notification-service-circuitbreaker
                    fallbackUri: /fallback/karvio-notification-service-fallback

resilience4j:
  circuitbreaker:
    instances:
      karvio-auth-service-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
      karvio-car-service-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
      karvio-document-service-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
      karvio-notification-service-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
  timelimiter:
    instances:
      karvio-auth-service-circuitbreaker:
        timeoutDuration: 10s
      karvio-car-service-circuitbreaker:
        timeoutDuration: 10s
      karvio-document-service-circuitbreaker:
        timeoutDuration: 10s
      karvio-notification-service-circuitbreaker:
        timeoutDuration: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"